// documentation/src/content/docs/guides/react/appearance.jsx
import { createTask, tag } from "@app-compose/core"
import { useStore } from "@nanostores/react"
import { selectedLanguage } from "./shared-tags"

const titles = {
  en: "Appearance",
  zh: "外观",
  hi: "रूप",
  es: "Apariencia",
  fr: "Apparence",
}

// tag: { Widget, key }[]
const appearanceWidgets = tag("appearanceWidgets")

const Appearance = createTask({
  name: "Appearance",
  run: {
    context: {
      widgets: appearanceWidgets.value,
      $selectedLanguage: selectedLanguage.value,
    },
    fn: (ctx) => {
      const Layout = () => {
        const lang = useStore(ctx.$selectedLanguage)

        return (
          <section>
            <h1>{titles[lang]}</h1>
            <div style={{ display: "flex", flexDirection: "column", gap: 8, alignItems: "center" }}>
              {ctx.widgets.map(({ Widget, key }) => (
                <Widget key={key} />
              ))}
            </div>
          </section>
        )
      }

      return { ui: { Layout } }
    },
  },
})

export { appearanceWidgets, Appearance }

// documentation/src/content/docs/guides/vue/appearance.vue
<script setup>
import { useStore } from "@nanostores/vue"

const props = defineProps({
  widgets: { type: Array, required: true },
  languageAtom: { type: Object, required: true },
})

const lang = useStore(props.languageAtom)

const titles = {
  en: "Appearance",
  zh: "外观",
  hi: "रूप",
  es: "Apariencia",
  fr: "Apparence",
}
</script>

<template>
  <section>
    <h1>{{ titles[lang] }}</h1>
    <div style="display: flex; flex-direction: column; gap: 8px; align-items: center">
      <component :is="w.Widget" v-for="w in widgets" :key="w.key" />
    </div>
  </section>
</template>
