// documentation/src/content/docs/guides/react/theme-provider.jsx
import { createTask } from "@app-compose/core"
import { useStore } from "@nanostores/react"
import { useEffect } from "react"
import { selectedTheme } from "./shared-tags"

const ThemeProvider = createTask({
  name: "ThemeProvider",
  run: {
    context: { $theme: selectedTheme.value },
    fn: (ctx) => {
      const Provider = ({ children }) => {
        const theme = useStore(ctx.$theme)

        useEffect(() => {
          document.body.style.background = theme === "dark" ? "#222" : "#fff"
          document.body.style.color = theme === "dark" ? "#eee" : "#111"
        }, [theme])

        return <>{children}</>
      }

      return { ui: { Provider } }
    },
  },
})

export { ThemeProvider }

// documentation/src/content/docs/guides/vue/theme-provider.vue
<script setup>
import { useStore } from "@nanostores/vue"
import { onScopeDispose, watchEffect } from "vue"

const props = defineProps({ atom: { type: Object, required: true } })
const theme = useStore(props.atom)

watchEffect(() => {
  const dark = theme.value === "dark"
  document.body.style.background = dark ? "#222" : "#fff"
  document.body.style.color = dark ? "#eee" : "#111"
})

onScopeDispose(() => {
  document.body.style.background = ""
  document.body.style.color = ""
})
</script>

<template>
  <slot />
</template>
